language: node_js
node_js:
- 8.1.3
before_install:
- openssl aes-256-cbc -K $encrypted_4f9e3f7f0556_key -iv $encrypted_4f9e3f7f0556_iv
  -in .travis/id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
after_script:
- scp -o StrictHostKeyChecking=no ../wxmarket root@39.108.164.254:~/../usr/local/project
